default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: reproduce_sequel_millisecond_truncation_development
  port:     <%= ENV["BOXEN_POSTGRESQL_PORT"] || 5432 %>
  host:     localhost

test:
  <<: *default
  database: reproduce_sequel_millisecond_truncation_test
  port:     <%= ENV["BOXEN_POSTGRESQL_PORT"] || 5432 %>
  host:     localhost

